version: "3.8"

services:
    authPostgresDB:
        image: postgres
        environment:
            POSTGRES_DB: users
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        networks:
            - authDB

    authService:
        image: sunset01/idp-auth-service:0.0.2
        environment:
            spring.datasource.url: jdbc:postgresql://authPostgresDB:5432/users
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: admin
        ports:
            - "8080:8080"
        networks:
            - logging
            - authDB
            - internal

    pgAdmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        networks:
            - authDB
            - internal

    kong:
        image: kong
        volumes:
            - ../kong:/usr/local/kong/declarative
        environment:
            KONG_DATABASE: "off"
            KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
        ports:
            - "8000:8000"
            - "8443:8443"
        networks:
            - internal

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - logging

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        networks:
            - logging

networks:
    logging:
    authDB:
    internal:
